### ISSUE TITLE
When loggin in after an error, the app crashes

### ISSUE THREAD

**Issue by elgervb** [TuvokVersatileKolinahr/hunaJS#37]
First login with a wrong password, then try to login correctly. 
Following error occures:

error: "TypeError: Cannot read property '0' of null↵    at ib.functionCall (http://localhost:4000/js/vendor/vendor.js:199:317)↵    at Ec.(anonymous function).compile.d.on.f (http://localhost:4000/js/vendor/vendor.js:216:74)↵    at n.$get.n.$eval (http://localhost:4000/js/vendor/vendor.js:126:15)↵    at n.$get.n.$apply (http://localhost:4000/js/vendor/vendor.js:126:241)↵    at HTMLFormElement.<anonymous> (http://localhost:4000/js/vendor/vendor.js:216:126)↵    at HTMLFormElement.c (http://localhost:4000/js/vendor/vendor.js:32:389)"

**Comment by tuvokki** [comment]
This issue was moved to TuvokVersatileKolinahr/Huna_Server#24
