### ISSUE TITLE
override error handler for Angular JS

### ISSUE THREAD

**Issue by tuvokki** [TuvokVersatileKolinahr/hunaJS#9]
Like this one in https://docs.angularjs.org/api/ng/service/$exceptionHandler

**Comment by elgervb** [comment]
Create modules for different JS frameworks. Start with AngularJS

**Comment by elgervb** [comment]
Also update script generation in host settings page

**Comment by tuvokki** [comment]
This issue was moved to TuvokVersatileKolinahr/Huna_Server#18
